# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [47]:
#Type your code here
import pandas as pd
import plotly.graph_objs as go
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [29]:
# Mengunduh dataset karyawan dari sumber eksternal (GitHub)
path = '../employee_data.csv'

# Membaca dataset ke dalam DataFrame menggunakan pandas
df = pd.read_csv(path)

In [30]:
df.head(10)  # Menampilkan 10 baris pertama dari DataFrame

,EmployeeId,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,38,NaN,Travel_Frequently,1444,Human Resources,1,4,Other,1,...,2,80,1,7,2,3,6,2,1,2
1,2,37,1.0,Travel_Rarely,1141,Research & Development,11,2,Medical,1,...,1,80,0,15,2,1,1,0,0,0
2,3,51,1.0,Travel_Rarely,1323,Research & Development,4,4,Life Sciences,1,...,3,80,3,18,2,4,10,0,2,7
3,4,42,0.0,Travel_Frequently,555,Sales,26,3,Marketing,1,...,4,80,1,23,2,4,20,4,4,8
4,5,40,NaN,Travel_Rarely,1194,Research & Development,2,4,Medical,1,...,2,80,3,20,2,3,5,3,0,2
5,6,29,NaN,Travel_Rarely,352,Human Resources,6,1,Medical,1,...,4,80,0,1,3,3,1,0,0,0
6,7,40,0.0,Travel_Rarely,1124,Sales,1,2,Medical,1,...,3,80,3,6,2,2,4,3,0,2
7,8,55,1.0,Travel_Rarely,725,Research & Development,2,3,Medical,1,...,4,80,1,24,2,3,5,2,1,4
8,9,36,0.0,Travel_Frequently,635,Research & Development,18,1,Medical,1,...,1,80,0,8,2,3,8,1,1,7
9,10,32,0.0,Travel_Rarely,1018,Research & Development,3,2,Life Sciences,1,...,4,80,0,10,6,3,7,7,7,7

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

In [31]:
#Type your code here
# Kondisi data
print("Info Dataset:")
df.info()

Info Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeId                1470 non-null   int64
 1   Age                       1470 non-null   int64
 2   Attrition                 1058 non-null   float64
 3   BusinessTravel            1470 non-null   object
 4   DailyRate                 1470 non-null   int64
 5   Department                1470 non-null   object
 6   DistanceFromHome          1470 non-null   int64
 7   Education                 1470 non-null   int64
 8   EducationField            1470 non-null   object
 9   EmployeeCount             1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(1), int64(26), object(8)
memory usage: 402.1+ KB

In [32]:
# Tampilkan statistik deskriptif
print("\nStatistik Deskriptif:")
df.describe()

Statistik Deskriptif:

,EmployeeId,Age,Attrition,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1058.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,735.500000,36.923810,0.169187,802.485714,9.192517,2.912925,1.0,2.721769,65.891156,2.729932,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,424.496761,9.135373,0.375094,403.509100,8.106864,1.024165,0.0,1.093082,20.329428,0.711561,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,1.000000,18.000000,0.000000,102.000000,1.000000,1.000000,1.0,1.000000,30.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,368.250000,30.000000,0.000000,465.000000,2.000000,2.000000,1.0,2.000000,48.000000,2.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,735.500000,36.000000,0.000000,802.000000,7.000000,3.000000,1.0,3.000000,66.000000,3.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,1102.750000,43.000000,0.000000,1157.000000,14.000000,4.000000,1.0,4.000000,83.750000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,1470.000000,60.000000,1.000000,1499.000000,29.000000,5.000000,1.0,4.000000,100.000000,4.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [33]:
# Menelusuri setiap kolom dalam DataFrame untuk analisis awal
for nama_kolom in df.columns:
    # Menampilkan jumlah nilai unik dari masing-masing kolom
    total_unik = df[nama_kolom].nunique()
    print(f"{nama_kolom}: Total data unik = {total_unik}")
    print("-" * 60)

EmployeeId: Total data unik = 1470
------------------------------------------------------------
Age: Total data unik = 43
------------------------------------------------------------
Attrition: Total data unik = 2
------------------------------------------------------------
BusinessTravel: Total data unik = 3
------------------------------------------------------------
DailyRate: Total data unik = 886
------------------------------------------------------------
Department: Total data unik = 3
------------------------------------------------------------
DistanceFromHome: Total data unik = 29
------------------------------------------------------------
Education: Total data unik = 5
------------------------------------------------------------
EducationField: Total data unik = 6
------------------------------------------------------------
EmployeeCount: Total data unik = 1
------------------------------------------------------------
EnvironmentSatisfaction: Total data unik = 4
------------------------------------------------------------
Gender: Total data unik = 2
------------------------------------------------------------
HourlyRate: Total data unik = 71
------------------------------------------------------------
JobInvolvement: Total data unik = 4
------------------------------------------------------------
JobLevel: Total data unik = 5
------------------------------------------------------------
JobRole: Total data unik = 9
------------------------------------------------------------
JobSatisfaction: Total data unik = 4
------------------------------------------------------------
MaritalStatus: Total data unik = 3
------------------------------------------------------------
MonthlyIncome: Total data unik = 1349
------------------------------------------------------------
MonthlyRate: Total data unik = 1427
------------------------------------------------------------
NumCompaniesWorked: Total data unik = 10
------------------------------------------------------------
Over18: Total data unik = 1
------------------------------------------------------------
OverTime: Total data unik = 2
------------------------------------------------------------
PercentSalaryHike: Total data unik = 15
------------------------------------------------------------
PerformanceRating: Total data unik = 2
------------------------------------------------------------
RelationshipSatisfaction: Total data unik = 4
------------------------------------------------------------
StandardHours: Total data unik = 1
------------------------------------------------------------
StockOptionLevel: Total data unik = 4
------------------------------------------------------------
TotalWorkingYears: Total data unik = 40
------------------------------------------------------------
TrainingTimesLastYear: Total data unik = 7
------------------------------------------------------------
WorkLifeBalance: Total data unik = 4
------------------------------------------------------------
YearsAtCompany: Total data unik = 37
------------------------------------------------------------
YearsInCurrentRole: Total data unik = 19
------------------------------------------------------------
YearsSinceLastPromotion: Total data unik = 16
------------------------------------------------------------
YearsWithCurrManager: Total data unik = 18
------------------------------------------------------------

In [34]:
print("\nJumlah df per Kategori Attrition:")
print(df['Attrition'].value_counts())

Jumlah df per Kategori Attrition:
Attrition
0.0    879
1.0    179
Name: count, dtype: int64

In [35]:
print("\nJumlah Data Null")
print(df.isna().sum())

Jumlah Data Null
EmployeeId                    0
Age                           0
Attrition                   412
BusinessTravel                0
DailyRate                     0
Department                    0
DistanceFromHome              0
Education                     0
EducationField                0
EmployeeCount                 0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 0
MonthlyIncome                 0
MonthlyRate                   0
NumCompaniesWorked            0
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating             0
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel              0
TotalWorkingYears             0
TrainingTimesLastYear         0
WorkLifeBalance               0
YearsAtCompany                0
YearsInCurrentRole            0
YearsSinceLastPromotion       0
YearsWithCurrManager          0
dtype: int64

In [36]:
# Drop data dengan nilai null
df.dropna(inplace=True)

In [37]:
# Menyimpan nama-nama kolom bertipe object dengan nilai unik ≤ 30 ke dalam list
kolom_kategorikal = []

# Menelusuri setiap kolom dalam DataFrame
for kolom in df.columns:
    # Mengecek apakah kolom bertipe object dan memiliki nilai unik kurang dari atau sama dengan 30
    if df[kolom].dtype == object and len(df[kolom].unique()) <= 30:
        kolom_kategorikal.append(kolom)  # Menambahkan ke dalam list
        print(f"{kolom} : Daftar nilai unik = {df[kolom].unique()}")
        print("Frekuensi masing-masing nilai:")
        print(df[kolom].value_counts())
        print("-" * 40)

BusinessTravel : Daftar nilai unik = ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
Frekuensi masing-masing nilai:
BusinessTravel
Travel_Rarely        746
Travel_Frequently    205
Non-Travel           107
Name: count, dtype: int64
----------------------------------------
Department : Daftar nilai unik = ['Research & Development' 'Sales' 'Human Resources']
Frekuensi masing-masing nilai:
Department
Research & Development    701
Sales                     319
Human Resources            38
Name: count, dtype: int64
----------------------------------------
EducationField : Daftar nilai unik = ['Medical' 'Life Sciences' 'Marketing' 'Technical Degree'
 'Human Resources' 'Other']
Frekuensi masing-masing nilai:
EducationField
Life Sciences       436
Medical             330
Marketing           122
Technical Degree     96
Other                59
Human Resources      15
Name: count, dtype: int64
----------------------------------------
Gender : Daftar nilai unik = ['Female' 'Male']
Frekuensi masing-masing nilai:
Gender
Male      620
Female    438
Name: count, dtype: int64
----------------------------------------
JobRole : Daftar nilai unik = ['Healthcare Representative' 'Research Scientist' 'Sales Executive'
 'Manager' 'Laboratory Technician' 'Research Director'
 'Manufacturing Director' 'Human Resources' 'Sales Representative']
Frekuensi masing-masing nilai:
JobRole
Sales Executive              232
Research Scientist           214
Laboratory Technician        188
Manufacturing Director       107
Healthcare Representative     88
Manager                       79
Research Director             62
Sales Representative          58
Human Resources               30
Name: count, dtype: int64
----------------------------------------
MaritalStatus : Daftar nilai unik = ['Married' 'Single' 'Divorced']
Frekuensi masing-masing nilai:
MaritalStatus
Married     464
Single      352
Divorced    242
Name: count, dtype: int64
----------------------------------------
Over18 : Daftar nilai unik = ['Y']
Frekuensi masing-masing nilai:
Over18
Y    1058
Name: count, dtype: int64
----------------------------------------
OverTime : Daftar nilai unik = ['No' 'Yes']
Frekuensi masing-masing nilai:
OverTime
No     751
Yes    307
Name: count, dtype: int64
----------------------------------------

In [38]:
# Hitung jumlah kolom
len(kolom_kategorikal)

8

In [39]:
# Mengonversi semua kolom bertipe float64 menjadi int64
kolom_float = df.select_dtypes(include='float64').columns  # Mengambil nama-nama kolom float64
df = df.astype({nama: 'int64' for nama in kolom_float})  # Melakukan konversi tipe data

In [40]:
# Menyimpan nama kolom numerik dengan jumlah nilai unik kurang dari 30
fitur_diskrit = []

# Melakukan iterasi pada setiap kolom di DataFrame
for kolom in df.columns:
    # Memastikan kolom bertipe numerik dan jumlah nilai uniknya < 30
    if df[kolom].dtypes != object and df[kolom].nunique() < 30:
        print(f"{kolom} : Daftar nilai unik = {df[kolom].unique()}")
        fitur_diskrit.append(kolom)  # Tambahkan ke list fitur diskrit
        print("-" * 40)

# Menghapus kolom 'Attrition' jika termasuk dalam daftar fitur diskrit
if 'Attrition' in fitur_diskrit:
    fitur_diskrit.remove('Attrition')

Attrition : Daftar nilai unik = [1 0]
----------------------------------------
DistanceFromHome : Daftar nilai unik = [11  4 26  1  2 18  3 23 12  6  5 10  8 13 14  7 16 21 22  9 28 20 17 24
 25 15 27 19 29]
----------------------------------------
Education : Daftar nilai unik = [2 4 3 1 5]
----------------------------------------
EmployeeCount : Daftar nilai unik = [1]
----------------------------------------
EnvironmentSatisfaction : Daftar nilai unik = [1 3 2 4]
----------------------------------------
JobInvolvement : Daftar nilai unik = [1 3 2 4]
----------------------------------------
JobLevel : Daftar nilai unik = [2 1 4 5 3]
----------------------------------------
JobSatisfaction : Daftar nilai unik = [2 3 4 1]
----------------------------------------
NumCompaniesWorked : Daftar nilai unik = [5 9 2 1 3 0 7 4 6 8]
----------------------------------------
PercentSalaryHike : Daftar nilai unik = [15 12 14 22 13 19 11 16 17 18 20 21 24 23 25]
----------------------------------------
PerformanceRating : Daftar nilai unik = [3 4]
----------------------------------------
RelationshipSatisfaction : Daftar nilai unik = [1 3 4 2]
----------------------------------------
StandardHours : Daftar nilai unik = [80]
----------------------------------------
StockOptionLevel : Daftar nilai unik = [0 3 1 2]
----------------------------------------
TrainingTimesLastYear : Daftar nilai unik = [2 6 1 3 4 5 0]
----------------------------------------
WorkLifeBalance : Daftar nilai unik = [1 4 2 3]
----------------------------------------
YearsInCurrentRole : Daftar nilai unik = [ 0  4  3  2  1  7 11  5  6 12  9  8 10 15 14 13 16 18 17]
----------------------------------------
YearsSinceLastPromotion : Daftar nilai unik = [ 0  2  4  1  7  8 11  5 15  3 10 12  6  9 13 14]
----------------------------------------
YearsWithCurrManager : Daftar nilai unik = [ 0  7  8  2  4  3  5  9 10 13 11  6  1 14 15 16 12 17]
----------------------------------------

In [41]:
# Menyusun daftar kolom numerik kontinu (nilai unik > 30)
fitur_kontinu = []

# Menelusuri setiap kolom dalam DataFrame
for kolom in df.columns:
    # Memastikan kolom bertipe numerik dan memiliki lebih dari 30 nilai unik
    if df[kolom].dtypes != object and df[kolom].nunique() > 30:
        nilai_min = df[kolom].min()
        nilai_max = df[kolom].max()
        print(f"{kolom} : Rentang nilai = {nilai_min} s.d. {nilai_max}")
        fitur_kontinu.append(kolom)  # Tambahkan kolom ke dalam list fitur kontinu
        print("-" * 40)

EmployeeId : Rentang nilai = 2 s.d. 1470
----------------------------------------
Age : Rentang nilai = 18 s.d. 60
----------------------------------------
DailyRate : Rentang nilai = 102 s.d. 1499
----------------------------------------
HourlyRate : Rentang nilai = 30 s.d. 100
----------------------------------------
MonthlyIncome : Rentang nilai = 1009 s.d. 19999
----------------------------------------
MonthlyRate : Rentang nilai = 2094 s.d. 26999
----------------------------------------
TotalWorkingYears : Rentang nilai = 0 s.d. 40
----------------------------------------
YearsAtCompany : Rentang nilai = 0 s.d. 40
----------------------------------------

In [42]:
# Fungsi bantu untuk menyesuaikan dimensi visualisasi plot
def atur_ukuran_plot(figur, lebar=600, tinggi=400):
    # Menetapkan ukuran layout (lebar dan tinggi) untuk objek plot
    figur.update_layout(width=lebar, height=tinggi)

In [43]:
# Memisahkan data menjadi dua kelompok: keluar (attrition) dan tetap bekerja
keluar = df[df['Attrition'] != 0]
tetap = df[df['Attrition'] == 0]

# ------------ CETAK STATISTIK -----------------------
# Menghitung jumlah total data, jumlah karyawan keluar, dan yang tetap
jumlah_total = len(df)
jumlah_keluar = len(keluar)
jumlah_tetap = len(tetap)

# Menghitung persentase masing-masing
persen_keluar = jumlah_keluar / jumlah_total * 100
persen_tetap = jumlah_tetap / jumlah_total * 100

# Menampilkan informasi jumlah dan persentase attrition
print(f"Karyawan Keluar     : {jumlah_keluar} ({persen_keluar:.2f}%)")
print(f"Karyawan Tetap      : {jumlah_tetap} ({persen_tetap:.2f}%)\n")


# ------------ BAR PLOT (Jumlah karyawan keluar vs tetap) -----------------------
bar_data = go.Bar(
    x=(jumlah_keluar, jumlah_tetap),                 # Jumlah masing-masing kategori
    y=['Keluar', 'Tetap'],                           # Label untuk sumbu Y
    orientation='h',                                 # Batang horizontal
    opacity=0.85,
    marker=dict(
        color=['salmon', 'mediumseagreen'],          # Warna batang diubah
        line=dict(color='#333333', width=1.2)        # Garis tepi lebih halus
    )
)

bar_layout = go.Layout(title='Jumlah Karyawan: Keluar vs Tetap')
fig = go.Figure(data=[bar_data], layout=bar_layout)
atur_ukuran_plot(fig)  # Gunakan fungsi yang sudah dimodifikasi sebelumnya
fig.show()


# ------------ PIE CHART (Distribusi attrition) -------------------
pie_data = go.Pie(
    labels=['Tetap', 'Keluar'],
    values=[jumlah_tetap, jumlah_keluar],
    textfont=dict(size=14),
    opacity=0.9,
    marker=dict(
        colors=['mediumseagreen', 'salmon'],         # Warna diubah agar beda dari versi awal
        line=dict(color='#333333', width=1.2)
    )
)

pie_layout = go.Layout(title='Distribusi Karyawan Berdasarkan Attrition')
fig = go.Figure(data=[pie_data], layout=pie_layout)
atur_ukuran_plot(fig)
fig.show()

Karyawan Keluar     : 179 (16.92%)
Karyawan Tetap      : 879 (83.08%)

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

In [45]:
print(df.shape)

(1058, 35)

In [48]:
# Membuat objek LabelEncoder
label_encoder = LabelEncoder()

# Inisialisasi penghitung kolom yang berhasil di-encode
jumlah_label_encoded = 0

# Loop untuk menerapkan encoding hanya pada kolom kategorikal dengan <= 2 nilai unik
for kolom in df.columns[1:]:  # Melewati kolom pertama (misal ID)
    if df[kolom].dtype == 'object':
        if len(df[kolom].unique()) <= 2:
            label_encoder.fit(df[kolom])
            df[kolom] = label_encoder.transform(df[kolom])
            jumlah_label_encoded += 1

# Menampilkan hasil jumlah kolom yang telah di-label encoding
print(f"{jumlah_label_encoded} kolom berhasil dikodekan menggunakan Label Encoding.")

3 kolom berhasil dikodekan menggunakan Label Encoding.

In [49]:
# Mengubah variabel kategorikal menjadi representasi numerik (dummy variables)
# drop_first=True digunakan untuk menghindari dummy variable trap
df = pd.get_dummies(df, prefix_sep='_', drop_first=True)

In [50]:
print(df.shape)
df.head()

(1058, 49)

,EmployeeId,Age,Attrition,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,Gender,HourlyRate,...,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single
1,2,37,1,1141,11,2,1,1,0,61,...,False,False,False,False,False,False,False,False,True,False
2,3,51,1,1323,4,4,1,1,1,34,...,False,False,False,False,False,True,False,False,True,False
3,4,42,0,555,26,3,1,3,0,77,...,False,False,False,False,False,False,True,False,True,False
6,7,40,0,1124,1,2,1,2,1,57,...,False,False,False,False,False,False,True,False,True,False
7,8,55,1,725,2,3,1,4,1,78,...,False,False,True,False,False,False,False,False,True,False

In [51]:
# Normalisasi fitur numerik ke dalam rentang 0 sampai 5 menggunakan MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 5))

# Membuat daftar nama kolom (kecuali target 'Attrition') yang akan dinormalisasi
kolom_fitur = list(df.columns)
kolom_fitur.remove('Attrition')

# Melakukan normalisasi untuk setiap kolom fitur
for kolom in kolom_fitur:
    df[kolom] = df[kolom].astype(float)  # Pastikan tipe data float
    df[[kolom]] = scaler.fit_transform(df[[kolom]])  # Skalakan

# Pastikan kolom target dikonversi ke float (jika diperlukan)
df['Attrition'] = pd.to_numeric(df['Attrition'], downcast='float')

# Tampilkan 5 baris pertama sebagai hasil preview
df.head()

,EmployeeId,Age,Attrition,DailyRate,DistanceFromHome,Education,EmployeeCount,EnvironmentSatisfaction,Gender,HourlyRate,...,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single
1,0.000000,2.261905,1.0,3.718683,1.785714,1.25,0.0,0.000000,0.0,2.214286,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
2,0.003406,3.928571,1.0,4.370079,0.535714,3.75,0.0,0.000000,5.0,0.285714,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,5.0,0.0
3,0.006812,2.857143,0.0,1.621331,4.464286,2.50,0.0,3.333333,0.0,3.357143,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0
6,0.017030,2.619048,0.0,3.657838,0.000000,1.25,0.0,1.666667,5.0,1.928571,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0
7,0.020436,4.404762,1.0,2.229778,0.178571,2.50,0.0,5.000000,5.0,3.428571,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0

In [52]:
# Menyimpan target ke variabel terpisah
target = df['Attrition'].copy()

In [53]:
# let's remove the target feature and redundant features from the dataset
df.drop(['Attrition', 'EmployeeCount', 'EmployeeId',
            'StandardHours', 'Over18'], axis=1, inplace=True)
print('Ukuran dataset penuh: {}'.format(df.shape))

Ukuran dataset penuh: (1058, 44)

In [54]:
df.to_csv('employee_data_preprocessed.csv', index=False)